interface UIConstant {
  [key: string]: any;
}

export const UIConstants: UIConstant = {
  PROGRESS_CIRCLE_SIZE: 53,
  PROGRESS_CIRCLE_STROKE_WIDTH: 12,
  PROGRESS_CIRCLE_MAX_PROGRESS: 99,
  PROGRESS_CIRCLE_START_ANGLE: 0,
  PROGRESS_CIRCLE_FULL_ANGLE: 360,
  PROGRESS_FILLED_COLOR_START: '#2459AD',
  PROGRESS_FILLED_COLOR_END: '#0D2346',
  PROGRESS_UNFILLED_COLOR: 'rgba(225,225,225,0.9)',
  GRADIENT_X1: '16.15%',
  GRADIENT_Y1: '85.35%',
  GRADIENT_X2: '85.35%',
  GRADIENT_Y2: '16.15%',
  SAVE_ICON_COLOR: '#0D2346',
  PRIMARY_BUTTON_GRADIENT_COLORS: ['#FFFFFF', '#E8F0FC'],
  SWITCH_TRACK_COLOR_FALSE: 'rgb(194, 194, 194)',
  SWITCH_TRACK_COLOR_TRUE: 'rgba(17, 51, 106, 0.46)',
  SWITCH_THUMB_COLOR_TRUE: 'rgb(17, 51, 106)',
  SWITCH_THUMB_COLOR_FALSE: 'rgb(142, 142, 142)',
  PADDING: 12,
  RHYTHM: 12,
  DRAWER_REDUCED_TRANSPARENCY_FALLBACK: 'rgba(0, 0, 0, 0.3)',
  DRAWER_ANIMATION_VISIBLE_OFFSET: 0,
  DRAWER_ANIMATION_OPEN_DURATION: 250,
  DRAWER_ANIMATION_HIDDEN_OFFSET: -300,
  DRAWER_ANIMATION_CLOSE_DURATION: 200,
};

export const EDGES_ALL_SIDES = ['top', 'bottom', 'left', 'right'] as const;
export const EDGES_DRAWER_MENU = ['top', 'left', 'bottom'] as const;
