# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Force problematic RN pods to static libraries, not static frameworks.
# This is the important part for Xcode explicit modules / non-modular header errors.
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.start_with?('RNFB') || ['RNSVG', 'RNScreens'].include?(pod.name)
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

target 'KhalisSehajPathApp' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
