import { StyleSheet } from 'react-native';
import font from '@utils/font';
import { UIConstants } from '@constants';

export const ChooseSlotStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: UIConstants.DRAWER_REDUCED_TRANSPARENCY_FALLBACK,
  },
  pickerOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: UIConstants.DRAWER_REDUCED_TRANSPARENCY_FALLBACK,
  },
  pickerCard: {
    minWidth: UIConstants.PADDING * 18,
    padding: UIConstants.PADDING,
    borderRadius: UIConstants.BORDER_RADIUS,
    backgroundColor: UIConstants.SURFACE_BACKGROUND,
    overflow: 'hidden',
    elevation: 8,
  },
  nativePicker: {
    backgroundColor: UIConstants.SURFACE_BACKGROUND,
  },
  pickerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: UIConstants.RHYTHM * 2,
    marginTop: UIConstants.RHYTHM,
  },
  pickerCancel: {
    color: UIConstants.MUTED_TEXT_COLOR,
    fontFamily: font.Baloo_Paaji_2_Medium,
    fontSize: UIConstants.BODY_FONT_SIZE,
  },
  pickerConfirm: {
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Extra_Bold,
    fontSize: UIConstants.BODY_FONT_SIZE,
  },
  sheet: {
    height: '75%',
    backgroundColor: UIConstants.SURFACE_BACKGROUND,
    borderTopLeftRadius: UIConstants.BORDER_RADIUS * 2,
    borderTopRightRadius: UIConstants.BORDER_RADIUS * 2,
  },
  grabber: {
    alignSelf: 'center',
    width: UIConstants.RHYTHM * 4,
    height: UIConstants.DIVIDER_HEIGHT * 5,
    marginTop: UIConstants.RHYTHM / 2,
    borderRadius: UIConstants.BORDER_RADIUS,
    backgroundColor: UIConstants.MUTED_TEXT_COLOR,
    opacity: 0.6,
  },
  grabberHitArea: {
    alignSelf: 'stretch',
    alignItems: 'center',
    paddingVertical: UIConstants.RHYTHM / 2,
  },
  content: {
    paddingHorizontal: UIConstants.PADDING + UIConstants.DIVIDER_HEIGHT * 4,
    paddingTop: UIConstants.RHYTHM,
    paddingBottom: UIConstants.RHYTHM * 2,
  },
  title: {
    alignSelf: 'center',
    marginBottom: UIConstants.RHYTHM,
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Extra_Bold,
    fontSize: UIConstants.SUBTITLE_FONT_SIZE,
  },
  sectionLabel: {
    marginTop: UIConstants.RHYTHM + UIConstants.DIVIDER_HEIGHT * 4,
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Extra_Bold,
    fontSize: UIConstants.BODY_FONT_SIZE,
  },
  field: {
    minHeight: UIConstants.PADDING * 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: UIConstants.RHYTHM,
    paddingHorizontal: UIConstants.PADDING,
    borderWidth: UIConstants.DIVIDER_HEIGHT,
    borderColor: UIConstants.INPUT_BORDER_COLOR,
    borderRadius: UIConstants.BORDER_RADIUS,
    backgroundColor: UIConstants.INPUT_BACKGROUND,
  },
  fieldText: {
    flex: 1,
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Medium,
    fontSize: UIConstants.BODY_FONT_SIZE,
    textAlign: 'center',
  },
  timePickerField: { justifyContent: 'center' },
  placeholder: { color: UIConstants.INPUT_PLACEHOLDER_COLOR },
  dayArrow: { paddingHorizontal: UIConstants.RHYTHM, paddingVertical: UIConstants.RHYTHM / 2 },
  dayArrowText: {
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Extra_Bold,
    fontSize: UIConstants.TITLE_FONT_SIZE,
  },
  available: {
    marginTop: UIConstants.RHYTHM,
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Medium,
    fontSize: UIConstants.CAPTION_FONT_SIZE,
  },
  unavailable: {
    marginTop: UIConstants.RHYTHM,
    color: UIConstants.MUTED_TEXT_COLOR,
    fontFamily: font.Baloo_Paaji_2_Medium,
    fontSize: UIConstants.CAPTION_FONT_SIZE,
  },
  durationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: UIConstants.RHYTHM,
    rowGap: UIConstants.RHYTHM,
    marginTop: UIConstants.RHYTHM,
  },
  duration: {
    width: '30%',
    minHeight: UIConstants.PADDING * 4,
    justifyContent: 'center',
    paddingVertical: UIConstants.RHYTHM / 2,
    borderWidth: UIConstants.DIVIDER_HEIGHT,
    borderColor: UIConstants.INPUT_BORDER_COLOR,
    borderRadius: UIConstants.BORDER_RADIUS,
    alignItems: 'center',
  },
  durationDisabled: { opacity: 0.35 },
  durationSelected: {
    borderColor: UIConstants.PRIMARY_COLOR,
    backgroundColor: UIConstants.PRIMARY_COLOR,
  },
  durationText: {
    color: UIConstants.PRIMARY_COLOR,
    fontFamily: font.Baloo_Paaji_2_Medium,
    fontSize: UIConstants.CAPTION_FONT_SIZE,
  },
  durationTextSelected: { color: UIConstants.NAV_TEXT_COLOR },
  durationTextDisabled: { color: UIConstants.MUTED_TEXT_COLOR },
  loading: { marginVertical: UIConstants.RHYTHM * 2 },
  empty: {
    marginVertical: UIConstants.RHYTHM,
    color: UIConstants.MUTED_TEXT_COLOR,
    fontFamily: font.Baloo_Paaji_2_Regular,
    fontSize: UIConstants.CAPTION_FONT_SIZE,
  },
  book: {
    minHeight: UIConstants.PADDING * 4,
    justifyContent: 'center',
    marginHorizontal: UIConstants.PADDING + UIConstants.DIVIDER_HEIGHT * 4,
    marginBottom: UIConstants.RHYTHM,
    paddingVertical: UIConstants.RHYTHM / 2,
    borderRadius: UIConstants.BORDER_RADIUS,
    backgroundColor: UIConstants.PRIMARY_COLOR,
    alignItems: 'center',
  },
  bookText: {
    color: UIConstants.NAV_TEXT_COLOR,
    fontFamily: font.Baloo_Paaji_2_Extra_Bold,
    fontSize: UIConstants.BODY_FONT_SIZE,
  },
  disabled: { opacity: 0.45 },
});
